#!/bin/sh

. "$(dirname "$0")/_/husky.sh"

while read line; do

# Skip comments

if [ "${line:0:1}" == "#" ]; then

continue

fi

if [ ${#line} -ge 74 ] || [ ${#line} -le 10 ]; then

echo "\033[0;31mCOMMIT REJECTED! 💬 The length of the message has to be between 10 and 74 characters."

exit 1

fi

done < "${1}"

exit 0
